Push Docker Image (from done folder)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,24 +1,16 @@
+
 name: Main workflow
 on: push
 env: # Set the secret as an input
   github_username: ${{ github.actor }}
   github_password: ${{ secrets.GITHUB_TOKEN }} # Must be made available to the workflow
   GIT_COMMIT: ${{ github.sha }}
+
 jobs:
   Build:
     runs-on: ubuntu-latest
     container: gradle:6-jdk11
     steps:
-      - name: Validate GitHub username is all lowercase
-        id: validate_lower
-        run: |
-          if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
-            echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
-            exit 1
-          else
-            echo "GitHub username format is valid."
-          fi
-        shell: bash
       - name: Clone down repository
         uses: actions/checkout@v4       
       - name: Build application
@@ -31,10 +23,10 @@ jobs:
           name: code
           path: .
           include-hidden-files: true
+
   Linting:
     runs-on: ubuntu-latest
-    needs: 
-        - Build
+    needs: [Build]
     steps:
       - name: Download code
         uses: actions/download-artifact@v4
@@ -48,6 +40,7 @@ jobs:
           # To report GitHub Actions status checks
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DISABLE_ERRORS: true
+
   Docker-image:
     runs-on: ubuntu-latest
     needs: [Build]
@@ -59,8 +52,16 @@ jobs:
       with:
         name: code
         path: .
-    - name: ls
-      run: ls -la ci
+    - name: Validate Docker username is all lowercase
+      id: validate_lower
+      run: |
+        if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
+          echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
+          exit 1
+        else
+          echo "Docker username format is valid."
+        fi
+      shell: bash
     - name: build docker
       run: bash ci/build-docker.sh
     - name: push docker
